Repository Losses/rune, pull requests merged in 2025-01, with the labels that each got.

#218 feat: Initialize the iOS support
  Cargo.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ios/Runner/AppDelegate.swift
  ios/Runner/Base.lproj/Main.storyboard
  ios/Runner/Info.plist
  ios/Runner/Runner.entitlements
  lib/utils/get_dir_path.dart
  lib/utils/ios_file_selector.dart
  native/hub/Cargo.toml
  native/hub/apple-bridge-library/Package.resolved
  native/hub/apple-bridge-library/Package.swift
  native/hub/apple-bridge-library/Sources/apple-bridge-library/apple-bridge-library.swift
  native/hub/apple-bridge-library/Sources/apple-bridge-library/bridging-header.h
  native/hub/apple-bridge-library/build.sh
  native/hub/apple-bridge-library/src/lib.swift
  native/hub/build.rs
  native/hub/src/apple_bridge/mod.rs
  native/hub/src/license.rs
  playback/Cargo.toml
  playback/src/controller.rs
  playback/src/lib.rs
Labels: R - enhancement

#220 feat(iOS): Support system media control
  Cargo.lock
  ios/Runner/AppDelegate.swift
  playback/Cargo.toml
  playback/src/controller.rs
  playback/src/dummy_souvlaki.rs
  playback/src/lib.rs
Labels: R - enhancement

#225 RE: fix: Build issues caused by importing swift-rs
  native/hub/Cargo.toml
  native/hub/build.rs
Labels: C - dependencies

#227 RE: fix(iOS): Support secure bookmarks
  pubspec.lock
  pubspec.yaml
Labels: C - dependencies

#229 Update JA, JA_Nise & JA_Kana
  lib/l10n/intl_ja.arb
  lib/l10n/intl_ja_Kana.arb
  lib/l10n/intl_ja_Nise.arb
Labels: C - l10n

#232 fix: Tray icon not working on Flatpak for Linux
  assets/linux-tray-dark.svg
  assets/linux-tray-light.svg
  lib/utils/tray_manager.dart
  pubspec.yaml
Labels: P - Linux, C - UI

#239 JA translation for remote device
  lib/l10n/intl_ja.arb
  lib/l10n/intl_ja_Kana.arb
  lib/l10n/intl_ja_Nise.arb
Labels: C - l10n
